name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup-bash:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run bash test scripts
      shell: bash
      run: |
        chmod +x ./test.sh
        ./test.sh

  setup-bash-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run bash test scripts
      shell: bash
      run: |
        chmod +x ./test.sh
        ./test.sh

  setup-pwsh:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run PowerShell Core test scripts
      run: ./test.ps1
      shell: pwsh

  setup-zsh:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Zsh image
      run: docker build -t zshell -f .github/Dockerfile .
    - name: running zsh test
      run: docker run zshell
